services:
  tutorial: 
    image: postgres:latest
    ports: 
      - 5431:5432
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: tutorialDB
  tutorial_pgadmin:
    image: dpage/pgadmin4
    container_name: tutorialadmin
    links:
      - tutorial
    environment:
      PGADMIN_DEFAULT_EMAIL: adminemail@mail.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
      PMA_PORT: 5432
      PMA_ARBITRARY: 1
    ports:
      - 8083:80
